version: '3.8'

networks:
  micro_network:
    external:
      name: micro_network

services:
  cards-api:
    container_name: cp-cards
    build:
      context: .
    ports:
    - "5002:5000"
    volumes:
      - .:/app
    networks:
      - micro_network
    restart: always
    environment:
      - PYTHONUNBUFFERED=1