version: '3.8'

networks:
  micro_network:
    external:
      name: micro_network

services:
  accounts-api:
    container_name: cp-accounts
    build:
      context: .
    ports:
    - "5001:5001"
    volumes:
      - .:/app
    networks:
      - micro_network
    restart: always