version: '3.8'

networks:
  micro_network:
    external:
      name: micro_network

services:
  posts-api:
    container_name: cp-posts
    build:
      context: .
    ports:
    - "5003:5003"
    volumes:
      - .:/app
    networks:
      - micro_network
    restart: always